#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker { image 'nginx' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}
